### ISSUE TITLE
What is the Cache Container about?

### ISSUE THREAD

**Issue by Oppodelldog** [chefkoch-dev/container-run#8]
Hey guys, can you tell me what the cache container is about?
Is it about having busybox attached to each container to access its tools?

**Comment by perprogramming** [comment]
Hey @Oppodelldog , the cache directory does provide the $HOME of the current user and/or root, because that is were a lot of tools put there caches (e.g. npm, composer, ...). The trick is, that this container is created only once on a machine, based on the hash of the current directory. So if you run the script for example on a build agent, you can reuse the cache for multiple builds.

**Comment by Oppodelldog** [comment]
Thanks for the info @perprogramming, we are partially using container-run on MAC OS where the command **sha1sum** cannot be found, so that question came up. What a nice feature.

**Comment by perprogramming** [comment]
Hey @Oppodelldog , there was indeed an open pull request enabling compatibility with macos (using shasum alternatively). We did not merged that yet because we weren't sure it is really needed. I just merged it, so it should work for you now! Cheers, Per

**Comment by Oppodelldog** [comment]
Thanks @perprogramming for merging :+1: 
We'll check it out.
